#questao 1

CREATE DATABASE sistema;

CREATE TABLE tbProdutos(
ID VARCHAR(6)NOT NULL,
NOME VARCHAR (100) NOT NULL,
DESCRICAO VARCHAR (150),
DESCONTO FLOAT ,
DATA_PRODUTO DATE NOT NULL, 
PRIMARY KEY (ID)
) ENGINE = innodb;

#questao 2

SELECT * FROM tbProdutos WHERE DATA_PRODUTO >= "2020-01-01" AND DATA_PRODUTO <="2021-08-15" ;

#questao 3

SELECT * FROM tbProdutos WHERE DATA_PRODUTO < "2020-01-01" OR DATA_PRODUTO >"2021-08-15" ;

#questao 4

CREATE TABLE tbNotas_Fiscais(
NUMERO VARCHAR(6)  NOT NULL,
VALOR FLOAT NOT NULL ,
fk_ID_tbPRODUTOS VARCHAR(6),
PRIMARY KEY (NUMERO)
) ENGINE = innodb;


ALTER TABLE tbnotas_fiscais ADD FOREIGN KEY(fk_ID_tbPRODUTOS) REFERENCES tbprodutos(ID);

#QUESTAO 5

SELECT * FROM tbnotas_fiscais WHERE fk_ID_tbPRODUTOS = '455644';

#QUESTAO 6 

ALTER TABLE tbnotas_fiscais CHANGE numero order_id VARCHAR(6);

#QUESTAO 7
UPDATE tbprodutos SET id=243924 WHERE id=455644;

#QUESTAO 8
ALTER TABLE tbprodutos MODIFY DESCONTO FLOAT NOT NULL;

ALTER TABLE `sistema`.`tbnotas_fiscais` 
ADD CONSTRAINT `notas_produtos`
  FOREIGN KEY (`fk_ID_tbPRODUTOS`)
  REFERENCES `sistema`.`tbprodutos` (`ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;